### ISSUE TITLE
Reading a J2K compressed NITF using python

### ISSUE THREAD

**Issue by solsbarry** [mdaus/nitro#11] opened 2016-05-23 13:30 UTC
Hello,

I have no trouble reading and using data from uncompressed NITF images using python, but I have some that are JPEG2000 compressed and I can't seem to load them. Here is my code up to the point where it reaches an error

```
from nitf import *

fname = 'path/to/file.NTF'
handle = IOHandle(fname)
reader = Reader()
record = reader.read(handle)
segment = record.getImages()[0]
imReader = reader.newImageReader(0)

The error I get is as follows:

    Exception Traceback (most recent call last)
    <ipython-input-27-1e81730e29ea> in <module>()
    4 record = reader.read(handle)
    5 segment = record.getImages()[0]
    ----> 6 imReader = reader.newImageReader(0)
    7 subheader = segment.subheader

    /usr/lib64/python2.7/site-packages/nitf/init.pyc in newImageReader(self, num)
    327 nbpp = int(self.record.getImages()[num]['numBitsPerPixel'])
    328 reader = nitropy.nitf_Reader_newImageReader(self.ref, num, self.error)
    --> 329 if not reader: raise Exception('Unable to get new ImageReader')
    330 return ImageReader(reader, nbpp)
    331

    Exception: Unable to get new ImageReader
```

Any help would be greatly appreciated. And if this can't be done in python, I would apreciate any help trying to implement it in c++. I have not worked with nitro outside python, but I will if I have too.

And I am using version 2.7 built from the code on source forge. Is there a reason to rebuild with the code here on github or is it the same.

Thanks

**Comment by solsbarry** [comment] 2016-05-23 14:52
Hi nevermind. I rebuilt with the code here, and everything seems to work fine.

**Comment by asylvest** [comment] 2016-05-23 15:13
Great - glad this worked!

**Comment by JohnLunzer** [comment] 2016-07-27 14:51
@solsbarry, can you detail what your rebuilding process looked like? what you did differently?

@asylvest, would be grateful if you had any insight into why this happens?

I'm running into this same error.

**Comment by solsbarry** [comment] 2016-08-05 16:56
Hi JL,

This conversation started somewhere else, so the context is not clear. 

I had built the code from a different location, and that was an older version that was giving me problems. Once I built the version here, it worked fine. I didn't have to do anything special.

My only suggestion would be make sure you are using the version of the code provided here. Even if you think you are, maybe you are using an older version. I would say delete what you have now, and then build from the code provided here.

**Comment by asylvest** [comment] 2016-08-05 18:20
John,

Can you confirm you are using the latest commit from the master branch?  Can you detail the exact error you're getting and what OS you are on?  Is it possible for you to post the image you're having trouble reading?

**Comment by QuiteAFoxtrot** [comment] 2017-12-19 04:34
Hello,

I'm having a very similar error, but recompiling using the code here didn't help me.  I pulled the latest zip from the master branch, and ran the following:

    python waf configure --enable-debugging --disable-matlab --disable-java --require-python --enable-64bit --prefix=installed

    python waf build
    python waf install

Then in my script I have a bit of code very similar to what the thread starter solsbarry posted with the same error:
Traceback (most recent call last):
  File "MyFile.py", line 153, in <module>
    main()
  File "MyFile.py", line 133, in main
    imReader = reader.newImageReader(0)
  File "/data/home/username/packages/nitro-master/installed/lib/python2.7/site-packages/nitf/__init__.py", line 357, in newImageReader
    if not reader: raise Exception('Unable to get new ImageReader')
Exception: Unable to get new ImageReader

One thing I might be doing differently is that in my python script MyFile.py at the top I do
    import sys
    sys.path.insert(1, "/data/home/oneills2/packages/nitro-master/installed/lib/python2.7/site-packages/")

so that I can 'import nitf'.  Could I have done something wrong in my configure options maybe?
I'm running this on an Ubuntu 14.04.5 LTS (GNU/Linux 3.16.0-77-generic x86_64)

**Comment by JonathanMeans** [comment] 2017-12-19 13:02
It's very likely you're not doing anything wrong, but just to be sure could you please show the exact code giving this error?

Are you able read [this sample NITF](https://six-library.s3.amazonaws.com/sicd_example_RMA_RGZERO_RE16I_IM16I.nitf)?

If so, are you able to share the image causing this issue?

**Comment by asylvest** [comment] 2017-12-19 13:24
Is the NITF you're trying to read J2K-compressed?  If so, set your `NITF_PLUGIN_PATH` environment variable to `<install dir>/share/nitf/plugins`

**Comment by QuiteAFoxtrot** [comment] 2017-12-19 15:20
Wow thanks for the fast replies guys.  I set the NITF_PLUGIN_PATH correctly, thank you, and it fixed the 'Unable to get new ImageReader' error, but now I have a new one.  Here is my code (with my paths sanitized):

    import os
    import sys
    sys.path.insert(1, "/data/home/username/packages/nitro-old/nitro-old/installed/lib/python2.7/site-packages/")
    sys.path.insert(1, "/data/home/username/packages/nitro-old/nitro-old/installed/lib/python2.7/site-packages/nitf/")
    from nitf import *

    target_parse_directories = ["/path_to_my_data/SELF-EVAL/NITF",
                                "/path_to_my_data/SELF-TEST/NITF",
                                "/path_to_my_data/TRAIN/NITF"
                                ]
    
    
    for target_dir in target_parse_directories:
        
        target_files = os.listdir(target_dir)
    
        for filename in target_files:
            
            if 'VIS.ntf.' in filename:
                
                filepath = os.path.join(target_dir, filename)
                
                handle = IOHandle(filepath)
                reader = Reader()
                
                record = reader.read(handle)
                segment = record.getImages()[0]
                
                subheader = segment.subheader
                
                imReader = reader.newImageReader(0)


Now the error I get is:
*** Error in `python': free(): invalid pointer: 0x00007fb6e43547c8 ***
Aborted (core dumped)

Also, it does appear I can parse the sample NITF you provided, JonathanMeans.  The data I'm trying to parse are NITF files from the WPAFB 2009 dataset, found here: https://www.sdms.afrl.af.mil/index.php?collection=wpafb2009

And I'll try and attach a sample for reference in just a second.

**Comment by JonathanMeans** [comment] 2017-12-19 17:40
I've started to dig into this, and it looks like a bug in a destructor somewhere. If you need to work with this before I finish, you could possibly inconveniently work around this by structuring your code so that all the image readers stay in scope until all of your work is complete.

**Comment by JonathanMeans** [comment] 2017-12-19 19:41
@QuiteAFoxtrot This should be fixed now.

**Comment by QuiteAFoxtrot** [comment] 2017-12-19 23:57
Hi Jonathan,

Thank you very much - I have successfully circumvented the issue and was able to get the image to be read.  However, even rebuilding with the latest from your recent commit and merge:


    imReader = reader.newImageReader(0)
    imReader = reader.newImageReader(0)

twice in a row results in a segfault again.  I suspect as you said it had something to do with the destructor, obviously now as I know not to do this I will avoid it and the package will work but I thought I should let you know.  An unsuspecting user might write a script where they use the first reader to just look at a segment then later attempt to create a new reader without getting rid of the first one or something, expecting it to be fine and it won't be.  Maybe not the best coding structure of course, but probably still counts as a bug.

Thanks again!  Really saved me on this one :)

**Comment by asylvest** [comment] 2017-12-20 02:04
@QuiteAFoxtrot thanks for confirming things are working for you now.  Let's keep this open until @JonathanMeans has a chance to address fixing when two `ImageReader`s are created so we don't forget.

**Comment by JonathanMeans** [comment] 2017-12-20 11:49
@QuiteAFoxtrot Are you certain this is the cause of the segfault? May I see the full code which produces the error, please?

**Comment by QuiteAFoxtrot** [comment] 2017-12-20 16:22
Hi @JonathanMeans ,

I have since modified my code and am running a big job which will take another day or two to complete, so I can't test for you right now, but I'll try and double-check on this as soon as I can.

Aside from double-checking for you, I am >95% certain that the code I used to still create this bug was exactly what I posted before (with updated paths to point to the new nitro-master I had installed, I can confirm this at least from looking at my current code), except I put a second copy of 'imReader = reader.newImageReader(0)' after the first one, just to see if it crashed, and it did.  Sorry for the delay, I'll run this check as soon as the current executing code finishes.

**Comment by JonathanMeans** [comment] 2017-12-20 17:10
Thanks for the extra info. Just wanted to verify, since I've been struggling to make it break myself. I'll keep digging.

**Comment by geospatialDev** [comment] 2018-02-07 16:09
Was the destructor issue fixed?

**Comment by JonathanMeans** [comment] 2018-02-07 16:41
@geospatialDev 
Not yet. I have another issue ahead of this one. I'll let you know when it's fixed.

If it's urgent, let me know, and I can ask about getting things re-prioritized.

**Comment by JonathanMeans** [comment] 2018-02-22 13:56
@geospatialDev  @QuiteAFoxtrot 

https://github.com/mdaus/nitro/pull/77 fixes a bug which may have been the cause of your destructor issue. I cannot verify, because I have been unable to reproduce the error in Python. Let me know if you're still having problems...

**Comment by JDanielSmith** [comment] 2020-07-20 19:03
JonathanMeans commented on Feb 22, 2018 "#77 fixes a bug which may have been the cause of your destructor issue. I cannot verify, because I have been unable to reproduce the error in Python. Let me know if you're still having problems..."

**Closed by JDanielSmith** 2020-07-20 19:03 UTC
